### ISSUE TITLE
Jenkins builds broken

### ISSUE THREAD

**Issue by bartekn** [stellar/developers#117]
It looks like changes to JS SDK broke builds:
```
ERROR: Unable to find the source file or directory /app/repos/js-stellar-sdk/libdocs

[12:50:29] 'generate-sdk-symbols' errored after 1.33 min
[12:50:29] Error: ERROR: Unable to find the source file or directory /app/repos/js-stellar-sdk/libdocs

    at formatError (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/format-error.js:20:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/app/node_modules/orchestrator/index.js:264:8)
    at /app/node_modules/orchestrator/index.js:275:23
    at finish (/app/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/app/node_modules/orchestrator/lib/runTask.js:29:3)
    at /app/gulpfile.babel.js:97:14
    at ChildProcess.<anonymous> (/app/gulp/code-symbol-tags.js:41:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
[12:50:29] 'src' errored after 1.4 min
```
@rice2000 @theaeolianmachine you may want to check it out.

**Comment by ire-and-curses** [comment]
I think it happened here: https://github.com/stellar/js-stellar-sdk/commit/bf3b62ec3ba2bbeca9c6659bff572e518b9c62b9

Timestamp indicates this commit was the last one before the [first failing build](https://buildmeister-v2.stellar-ops.com/job/stellar-developers/359/).

The commited file references a new `libdocs` directory, which is the same as mentioned in the error message.

Does the new directory need to be added to some blacklist of excluded directories for the developers site, or something like that?
